### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by BloodOfYou** [makisukurisu/ontu-schedule-bot#30]
Доброго дня,як варіант я би зробив для цього бота функція пересилання повідомлень в чат группи а не тільки в особисті повідомлення.

**Comment by makisukurisu** [comment]
Доброго дня! Ця функція доступна вже зараз.

Для цього — додайте бота в групу та напишіть команду /start, після цього — оберіть групу, як в особистих повідомленнях.
За замовчуванням бот почне надсилати повідомлення за 10 хвилин до пари (перевірити це можна так само командою /start, якщо у вас стоїть галочка на кнопці "Отримувати повідомлення перед парою", то вони будуть приходити).

![image](https://github.com/makisukurisu/ontu-schedule-bot/assets/49622129/d6f0409b-b5b5-41a8-a315-a4ddf10a8e0a)

В рамках покращення взаємодії з ботом — подивлюся, як автоматично запропонувати налаштувати бота при додаванні в групу.

Дякую за звернення, сподіваюсь, що це вам допомогло! (Якщо так — прошу закрити тікет)

**Comment by BloodOfYou** [comment]
Я мав на увазі щоб бот відправляв це все саме не в особисті повідомлення а в телеграм группу

**Comment by makisukurisu** [comment]
Так, я вас зрозумів.
Бот працює як в особистих, так і в групових чатах. Як приклад:

https://github.com/makisukurisu/ontu-schedule-bot/assets/49622129/c0a11354-5810-4484-9380-c73f8c64fe95

Створіть групу, чи додайте бота в вашу наявну групу, та використовуйте його там.

**Comment by BloodOfYou** [comment]
Дякую велике!
