### ISSUE TITLE
[FR] Change (update) notification flow

### ISSUE THREAD

**Issue by makisukurisu** [makisukurisu/ontu-schedule-bot#31]
**Is your feature request related to a problem? Please describe.**
Currently, bot takes about 180-250 seconds to send all the messages with schedule.
I propose to update this flow to use less resources.

**Describe the solution you'd like**
I see at least two ways for improvement.
1. Get all the subscriptions with enabled "send schedule" feature, and fetch only those subscriptions + send schedule for all groups of this subscription at the same time.
2. Download a list of all the schedules (or better yet - pairs) required for current messaging queue in one request, and send them. More details: Send a request to get all the schedule objects for all subscriptions with chat ids of who should receive what messages.

**Comment by hikionori** [comment]
Add integration with Google Calendar API. As an example, make it possible to add a weekly schedule to the calendar.

**Comment by hikionori** [comment]
I think that you can add an additional button to the message `/schedule`

Monday
Tuesday
Wednesday
Thursday
Friday
Add schedule to calendar 

This but call function that will generate url and redirect user to web page with google auth and add calendar, or generate [link for add to calendar](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://help.lafayette.edu/generate-a-url-to-add-events-to-google-calendar/&ved=2ahUKEwjuxNGWj7yBAxWY2gIHHYWjCeQQFnoECBEQAQ&usg=AOvVaw25pRhE4J3TcLjhURYkTj7f)

**Comment by makisukurisu** [comment]
Hi, @hikionori, can you please provide suggestions on the matter of Google Calendar in issue #32 ?

I'll try to implement this feature, since it seems to be pretty useful.
Thank you for your suggestion!

**Comment by hikionori** [comment]
> Hi, @hikionori, can you please provide suggestions on the matter of Google Calendar in issue #32 ?
> 
> I'll try to implement this feature, since it seems to be pretty useful.
> Thank you for your suggestion!

Maybe this will be useful [resource](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://developers.google.com/calendar/api/guides/create-events&ved=2ahUKEwjBtrfAkLyBAxWCgP0HHV-QCn4Q0gIoAXoECCIQAg&usg=AOvVaw31ILHz9UNf35ZENw47mCVW)

**Comment by makisukurisu** [comment]
Closing this issue as resolved.

And opening a new one, for WS batch schedule
